# Generated by Django 4.1 on 2022-08-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='line_charts1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=200)),
                ('pmm', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='database',
        ),
    ]
