# Generated by Django 4.1 on 2022-08-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_line_charts1_delete_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now=True, verbose_name='time')),
                ('pm25', models.FloatField(verbose_name='PM25')),
                ('average_temperature', models.FloatField(verbose_name='Average Temperature')),
                ('rain_precipitation', models.FloatField(verbose_name='Rain Precipitation')),
                ('wind_speed', models.FloatField(verbose_name='Wind speed')),
                ('Visibility', models.FloatField(verbose_name='Visibility')),
                ('cloudcover', models.FloatField(verbose_name='Cloudcover')),
                ('relative_humidity', models.FloatField(verbose_name='Relative_Humidity')),
                ('station', models.FloatField(verbose_name='Station')),
                ('division', models.CharField(max_length=255, verbose_name='Division')),
                ('Organization', models.CharField(max_length=255, verbose_name='Organization')),
                ('Season', models.CharField(max_length=255, verbose_name='Season')),
            ],
        ),
        migrations.DeleteModel(
            name='line_charts1',
        ),
    ]
